DROP TABLE ORDER_ITEM;
DROP TABLE ORDERS;
DROP TABLE ITEMS;

CREATE TABLE ITEMS (
    ID SERIAL PRIMARY KEY UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NAME VARCHAR(100),
    ICON VARCHAR(100),
    PRICE FLOAT
);

INSERT INTO ITEMS (NAME, ICON, PRICE) VALUES ('Crêpes nature', 'crepe_nature', .8);
INSERT INTO ITEMS (NAME, ICON, PRICE) VALUES ('Crêpes au sucre', 'crepe_sucre', 1);
INSERT INTO ITEMS (NAME, ICON, PRICE) VALUES ('Crêpes au nutella', 'crepe_nutella', 1.2);

CREATE TABLE ORDERS (
    ID SERIAL PRIMARY KEY UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PAID_LYDIA FLOAT,
    PAID_CASH FLOAT,
    GVBACK_LYDIA FLOAT,
    GVBACK_CASH FLOAT
);

CREATE TABLE ORDER_ITEM (
    ID SERIAL PRIMARY KEY UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ORDER_ID INTEGER REFERENCES ORDERS(ID),
    QUANTITY INTEGER
);
