DROP TABLE ORDER_OPERATION;
DROP TABLE ORDER_ITEM;
DROP TABLE ORDERS;
DROP TABLE ITEMS;

CREATE TABLE ITEMS (
    ID SERIAL PRIMARY KEY UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NAME VARCHAR(100),
    ICON VARCHAR(100),
    PRICE INTEGER
);

INSERT INTO ITEMS (NAME, ICON, PRICE) VALUES ('Crêpes nature', 'crepe_nature.jpg', 80);
INSERT INTO ITEMS (NAME, ICON, PRICE) VALUES ('Crêpes au sucre', 'crepe_sucre.jpg', 100);
INSERT INTO ITEMS (NAME, ICON, PRICE) VALUES ('Crêpes au nutella', 'crepe_nutella.jpeg', 120);

CREATE TABLE ORDERS (
    ID SERIAL PRIMARY KEY UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

INSERT INTO ORDERS;

CREATE TABLE ORDER_ITEM (
    ID         SERIAL PRIMARY KEY UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ORDER_ID   INTEGER REFERENCES ORDERS(ID),
    ITEM_ID    INTEGER REFERENCES ITEMS(ID),
    QUANTITY   INTEGER
);

INSERT INTO ORDER_ITEM(ORDER_ID, ITEM_ID, QUANTITY) VALUES (1, 1, 2);
INSERT INTO ORDER_ITEM(ORDER_ID, ITEM_ID, QUANTITY) VALUES (1, 3, 2);
INSERT INTO ORDER_ITEM(ORDER_ID, ITEM_ID, QUANTITY) VALUES (1, 2, 1);

-- OperationType:
-- 0: Recu par cash
-- 1: Recu par lydia
-- 2: Remboursé par cash
-- 3: Remboursé par lydia
CREATE TABLE ORDER_OPERATION (
    ID SERIAL PRIMARY KEY UNIQUE,
    OPERATION_TYPE INT,
    AMT INTEGER
);

INSERT INTO ORDER_OPERATION (OPERATION_TYPE, AMT) VALUES (1, 5.0)